# Generated by Django 4.1 on 2022-08-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('bio', models.TextField(verbose_name='')),
                ('socialmedia', models.TextField(verbose_name='')),
                ('category', models.CharField(max_length=100)),
                ('config', models.TextField(verbose_name='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LoginSystem.bluser')),
            ],
        ),
    ]
